Repository crossplatformkorea/react-native-kakao-login, pull requests merged in 2019-10, with the labels that each got.

#68 Migrate to @react-native-seoul/kakao-login
  CHANGELOG.md
  KakaoLoginExample/App.js
  KakaoLoginExample/ios/Podfile.lock
  KakaoLoginExample/package.json
  KakaoLoginExample/yarn.lock
  README.md
  package.json
  react-native-kakao-logins.podspec
Labels: release

#69 Migrate/typescript
  .eslintrc.js
  .gitignore
  README.md
  index.d.ts
  index.js
  index.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: migrate, release

#70 1.0.0-rc2 설치 실패 관련 버그 수정
  .npmignore
  CHANGELOG.md
  README.md
  kakao-login.podspec
  package.json
Labels: bugfix

#67 feat: support promises and error code
  KakaoLoginExample/.gitignore
  KakaoLoginExample/App.js
  KakaoLoginExample/android/app/debug.keystore
  KakaoLoginExample/ios/Podfile.lock
  KakaoLoginExample/package.json
  KakaoLoginExample/yarn.lock
  README.md
  android/src/main/java/com/dooboolab/kakaologins/RNKakaoLoginsModule.java
  index.ts
  ios/RNKakaoLogins/RNKakaoLogins.m
Labels: feature
