Repository crossplatformkorea/react-native-kakao-login, pull requests merged in 2021-05, with the labels that each got.

#219 Release 3.2.0
  CHANGELOG.md
  KakaoLoginExample/.github/publish-package.yml
  KakaoLoginExample/package.json
  KakaoLoginExample/yarn.lock
  android/build.gradle
  package.json
  yarn.lock
Labels: 📘 release, 🔥 hotfix

#226 index.ts 내의 getAccessToken 연결 변경
  index.ts
Labels: 🔥 hotfix

#227 docs: apply code highlighting to README
  README.md
Labels: 📖 documentation
