Repository crossplatformkorea/react-native-kakao-login, pull requests merged in 2021-11, with the labels that each got.

#255 Update README.md
  README.md
Labels: 📖 documentation

#261 잘못된 `KakaoProfile` 타입의 필드 이름을 변경합니다(`birthDay` -> `birthday`).
  index.ts
Labels: 🥢 typo

#262 Update README.md
  README.md
Labels: 📖 documentation

#270 android getProfile error fix
  android/src/main/java/com/dooboolab/kakaologins/RNKakaoLoginsModule.kt
  index.ts
Labels: 🍗 enhancement, 🤖 android

#274 getAccessToken의 token값이 잘못 되던것과 ios에서의 id가 number로 반환되는것을 수정했습니다.
  android/src/main/java/com/dooboolab/kakaologins/RNKakaoLoginsModule.kt
  ios/RNKakaoLogins/RNKakaoLogins.swift
Labels: 📱 iOS, 🤖 android
