Repository crossplatformkorea/react-native-kakao-login, pull requests merged in 2022-09, with the labels that each got.

#325 [BUGFIX] 네이티브 코드 수정
  .vscode/settings.json
  package.json
  src/index.native.ts
  src/index.ts
Labels: 🛠 bugfix

#328 카카오 SDK 버전 및 의존성 변경 (Xcode 14 빌드 지원)
  kakao-login.podspec
Labels: 👷‍♀️ build, 🛠 bugfix, 📱 iOS

#320 EXPO EAS 지원
  .eslintrc.js
  .gitignore
  README.md
  app.plugin.js
  package.json
  plugins/android/withAndroidKakaoLogin.ts
  plugins/index.ts
  plugins/ios/withIosKakaoLogin.ts
  plugins/tsconfig.json
Labels: 🎯 feature

#331 kakaoLogin으로 프로젝트 재생성하여 만들었습니다
  KakaoLoginExample/.ruby-version
  KakaoLoginExample/.watchmanconfig
  KakaoLoginExample/__tests__/App-test.tsx
  KakaoLoginExample/_node-version
  KakaoLoginExample/android/app/_BUCK
  KakaoLoginExample/android/app/build.gradle
  KakaoLoginExample/android/app/src/debug/java/com/kakaologin/ReactNativeFlipper.java
  KakaoLoginExample/android/app/src/main/AndroidManifest.xml
  KakaoLoginExample/android/app/src/main/java/com/kakaologin/MainActivity.java
  KakaoLoginExample/android/app/src/main/java/com/kakaologin/MainApplication.java
  KakaoLoginExample/android/app/src/main/java/com/kakaologin/newarchitecture/MainApplicationReactNativeHost.java
  KakaoLoginExample/android/app/src/main/java/com/kakaologin/newarchitecture/components/MainComponentsRegistry.java
  KakaoLoginExample/android/app/src/main/java/com/kakaologin/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  KakaoLoginExample/android/app/src/main/jni/Android.mk
  KakaoLoginExample/android/app/src/main/jni/CMakeLists.txt
  KakaoLoginExample/android/app/src/main/jni/MainApplicationModuleProvider.cpp
  KakaoLoginExample/android/app/src/main/jni/MainApplicationModuleProvider.h
  KakaoLoginExample/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  KakaoLoginExample/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  KakaoLoginExample/android/app/src/main/jni/MainComponentsRegistry.cpp
  KakaoLoginExample/android/app/src/main/jni/MainComponentsRegistry.h
  KakaoLoginExample/android/app/src/main/res/values/strings.xml
  KakaoLoginExample/android/build.gradle
  KakaoLoginExample/android/gradle/wrapper/gradle-wrapper.jar
  KakaoLoginExample/android/gradle/wrapper/gradle-wrapper.properties
  KakaoLoginExample/android/settings.gradle
  KakaoLoginExample/app.json
  KakaoLoginExample/ios/KakaoLogin-Bridging-Header.h
  KakaoLoginExample/ios/KakaoLogin.xcodeproj/project.pbxproj
  KakaoLoginExample/ios/KakaoLogin.xcodeproj/xcshareddata/xcschemes/KakaoLogin.xcscheme
  KakaoLoginExample/ios/KakaoLogin.xcworkspace/contents.xcworkspacedata
  KakaoLoginExample/ios/KakaoLogin.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  KakaoLoginExample/ios/KakaoLogin/AppDelegate.h
  KakaoLoginExample/ios/KakaoLogin/AppDelegate.mm
  KakaoLoginExample/ios/KakaoLogin/Images.xcassets/AppIcon.appiconset/Contents.json
  KakaoLoginExample/ios/KakaoLogin/Images.xcassets/Contents.json
  KakaoLoginExample/ios/KakaoLogin/Info.plist
  KakaoLoginExample/ios/KakaoLogin/LaunchScreen.storyboard
  KakaoLoginExample/ios/KakaoLogin/main.m
  KakaoLoginExample/ios/KakaoLoginTests/Info.plist
  KakaoLoginExample/ios/KakaoLoginTests/KakaoLoginTests.m
  KakaoLoginExample/ios/KakaoLoginWeb-Bridging-Header.h
  KakaoLoginExample/ios/Podfile
  KakaoLoginExample/ios/Podfile.lock
  KakaoLoginExample/package.json
  KakaoLoginExample/src/index.js
  KakaoLoginExample/yarn.lock
Labels: :spiral_notepad: example, 🔨 refactor
